0DIMG(99):Z=RND(-VAL(RIGHT$(TIME$,2))):FORF=6TO99:G(F)=-(F>9)*(RND(1)*4+2):NEXT:M=200:V=1:G$="*.":?
1T=T+1:L=V:FORI=1TO4:?"..";:V=G(6+L*4):G(I)=INT(INT(RND(1)*(V+I)+V)*5^I+.1):NEXT:?
2Z=RND(1):?:?"Day "T:?:RESTORE:FORI=1TO5:READS$:?I"="S$MID$(G$,2+(I=L),1):NEXT:?:FORI=6TO9:READS$
3?I"="S$,"$"G(I-5)G(I):NEXT:?:?"$"M:DATAHongkong,Shanghai,Nagasaki,Singapore
4INPUTV:IFV<1ORV>9ORV=LTHEN4ELSEIFV<6THEN9ELSEB=INT(M/G(V-5)):S=-G(V):IFB>FTHENB=F
5?"S:"S,"B:"B:INPUTQ:IFQ<SORQ>BTHEN5ELSEG(V)=G(V)+Q:F=F-Q:M=M-G(V-5)*Q:GOTO2
6?:?"Pirates:"Q:?D"% DMG>RET=*>1=Flee":INPUTR:IFR=0THEN7ELSEIFRND(1)<.4THEN1ELSE?"Fail";:GOTO8
7H=INT(RND(1)*Q/2)+1:Q=Q-H:?:?"We SINK"H;:IFQ=0THENM=M+T*10:?" & LOOT $"T*10
8IFQ=0THEN1ELSEH=INT(RND(1)*9):D=D+H:?", receive DMG "H:IFD<100THEN6ELSE?"DIED":END
9D=INT(D*.9):Q=INT(RND(1)*T/2)+3:ON1-(RND(1)<.4)GOTO1,6:DATAManila,Rice,Arms,Silk,Opium
