100?"{clr}   GALACTIC MAP    *     FLEET INFO"
101?"                   * CREDITS:       1000"
102?"  *                * TRANSPORTS: xxx/xxx "
103?"           *       * FIGHTERS:     xxx"
104?"                   * SUPPLY SHIPS: xxx"
105?"                   * SATTELITES:   xxx"
106?"                   * FUEL SHIPS:   xxx"
107?"                   * SUPPLIES: xxxx/xxxx"
108?"         *         * FUEL: XXXX/XXXX"
109?"    *              * "
110?"                   * INFO ON <planet>"
111?"                   * Status: Indep."
112?"                   * Tech:   unknown"
113?"                   * Pop:    xx m"
115?"******************** Sats:   0"
116?"ORBITING: GALACTICA| Space forces:  Unk." 
117?"Distance:  x       | Ground Forces: Unk."
118?"Status: Empire     | Potential cost: xyz"
119?"Tech:   adv.       | ALLOCS:  Prod  Curr"
120?"Pop:    xx mm      | Agr: XX%   XX  XXXX"
121?"                   | Eco: XX%   XX  XXXX"
122?"Star Date: 0.00    | Ind: XX%   XX  XXXX"
123?"Progress:          | Mil: XX%   XX  XXXX "
124?"E:1 O:10 I:9       | Min: XX%   XX  XXXX "
